name: Deploy Spring Boot App to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Spring Boot Application
        run: ./mvnw clean install -DskipTests

      - name: Find JAR File
        run: |
          jar_file=$(ls ./target/*.jar)
          echo "Found JAR file: $jar_file"
          echo "::set-env name=JAR_FILE::$jar_file"

      - name: Copy JAR to EC2
        run: scp -o StrictHostKeyChecking=no ${{ env.JAR_FILE }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/path/on/ec2/

      - name: SSH into EC2 and Restart Application
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_SSH_PORT }} 'sudo systemctl restart self_hosting_project.service'
